//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probet247.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class betfairbEntities : DbContext
    {
        public betfairbEntities()
            : base("name=betfairbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<live_bet> live_bet { get; set; }
    
        public virtual ObjectResult<AutoTp_Result> AutoTp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AutoTp_Result>("AutoTp");
        }
    
        public virtual ObjectResult<live_bet> AutoTpSPM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<live_bet>("AutoTpSPM");
        }
    
        public virtual ObjectResult<live_bet> AutoTpSPM(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<live_bet>("AutoTpSPM", mergeOption);
        }
    }
}
